### ISSUE TITLE
遇到错误

### ISSUE THREAD

**Issue by guayun** [z2z63/VChat#2]
python verison 3.12.3
D:\Desktop\vchat>python c.py
hot reload failed
No login status found, loading login status failed.
Traceback (most recent call last):
  File "D:\Desktop\vchat\c.py", line 24, in <module>
    asyncio.run(main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Desktop\vchat\c.py", line 16, in main
    await core.auto_login(hot_reload=True)
  File "C:\Users\guaxa\AppData\Roaming\Python\Python312\site-packages\vchat\core\register.py", line 51, in auto_login
    await self.login(
  File "C:\Users\guaxa\AppData\Roaming\Python\Python312\site-packages\vchat\core\login.py", line 43, in login
    resp_text = await self._get_uuid_and_wait_for_scan(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guaxa\AppData\Roaming\Python\Python312\site-packages\vchat\core\login.py", line 107, in _get_uuid_and_wait_for_scan
    await self.get_qr(self.uuid, enable_cmd_qr, pic_path, qr_callback)
  File "C:\Users\guaxa\AppData\Roaming\Python\Python312\site-packages\vchat\core\login.py", line 81, in get_qr
    utils.print_qr(pic_path)
  File "C:\Users\guaxa\AppData\Roaming\Python\Python312\site-packages\vchat\utils.py", line 96, in print_qr
    subprocess.call(["open", file_path])
  File "C:\Python312\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000193A2BF5A90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000193A30E23F0>, 1209665.921)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000193A3081280>

**Comment by z2z63** [comment]
v1.0.1已发布，解决了这个问题，文档也已经更新，更新vchat包即可解决问题
